name: circadian-scenes

services:
  homeassistant:
    container_name: circadian-scenes-ha
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    ports:
      - "8123:8123"
    environment:
      TZ: Europe/Oslo
    volumes:
      - ./dev/config:/config
      - ./custom_components/circadian_scenes:/config/custom_components/circadian_scenes:ro
