name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint black isort

      - name: Run pylint
        run: |
          pylint custom_components/scene_extrapolation/ --disable=C0114,C0116

      - name: Run black
        run: |
          black --check custom_components/scene_extrapolation/

      - name: Run isort
        run: |
          isort --check-only custom_components/scene_extrapolation/

  validate-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate manifest.json
        run: |
          # Check if manifest.json is valid JSON
          python -c "import json; json.load(open('custom_components/scene_extrapolation/manifest.json'))"

          # Check required fields
          python -c "
          import json
          manifest = json.load(open('custom_components/scene_extrapolation/manifest.json'))
          required_fields = ['domain', 'name', 'version', 'config_flow']
          for field in required_fields:
              if field not in manifest:
                  raise ValueError(f'Missing required field: {field}')
          print('Manifest validation passed')
          "

  validate-hacs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate hacs.json
        run: |
          # Check if hacs.json is valid JSON
          python -c "import json; json.load(open('hacs.json'))"
          echo "HACS configuration validation passed"
