name: Version and Release

on:
  push:
    tags:
      - "v*"

jobs:
  version-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master # Check out the main branch instead of the tag

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Check tag message for release trigger
        id: check_release
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          # Get the tag message using git show
          TAG_MESSAGE=$(git show --format='%B' -s "$TAG_NAME" 2>/dev/null || echo "")
          echo "Tag message: $TAG_MESSAGE"

          if echo "$TAG_MESSAGE" | grep -q "release=true"; then
            echo "should_release=true" >> $GITHUB_OUTPUT
            echo "✅ Release triggered by tag message"
          else
            echo "should_release=false" >> $GITHUB_OUTPUT
            echo "ℹ️  No release triggered (tag message doesn't contain 'release=true')"
          fi

      - name: Update manifest version
        run: |
          VERSION=${{ steps.version.outputs.version }}
          # Update manifest.json with the new version
          jq --arg version "$VERSION" '.version = $version' custom_components/scene_extrapolation/manifest.json > temp.json
          mv temp.json custom_components/scene_extrapolation/manifest.json
          echo "Updated manifest.json to version $VERSION"

      - name: Update CHANGELOG.md for release
        if: steps.check_release.outputs.should_release == 'true'
        id: update_changelog
        run: |
          VERSION=${{ steps.version.outputs.version }}
          DATE=$(date +%Y-%m-%d)

          # Create a temporary file for the updated changelog
          TEMP_CHANGELOG=$(mktemp)

          # Add header
          echo "# Changelog" > "$TEMP_CHANGELOG"
          echo "" >> "$TEMP_CHANGELOG"
          echo "All notable changes to this project will be documented in this file." >> "$TEMP_CHANGELOG"
          echo "" >> "$TEMP_CHANGELOG"
          echo "The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)," >> "$TEMP_CHANGELOG"
          echo "and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html)." >> "$TEMP_CHANGELOG"
          echo "" >> "$TEMP_CHANGELOG"

          # Add new Unreleased section
          echo "## [Unreleased]" >> "$TEMP_CHANGELOG"
          echo "" >> "$TEMP_CHANGELOG"
          echo "### Added" >> "$TEMP_CHANGELOG"
          echo "- " >> "$TEMP_CHANGELOG"
          echo "" >> "$TEMP_CHANGELOG"
          echo "### Changed" >> "$TEMP_CHANGELOG"
          echo "- " >> "$TEMP_CHANGELOG"
          echo "" >> "$TEMP_CHANGELOG"
          echo "### Fixed" >> "$TEMP_CHANGELOG"
          echo "- " >> "$TEMP_CHANGELOG"
          echo "" >> "$TEMP_CHANGELOG"

          # Add the released version (convert Unreleased to the new version)
          echo "## [$VERSION] - $DATE" >> "$TEMP_CHANGELOG"
          echo "" >> "$TEMP_CHANGELOG"

          # Extract the Unreleased section content and add it to the new version
          # Use sed to extract content between Unreleased and next version (more reliable)
          sed -n '/^## \[Unreleased\]/,/^## \[/p' CHANGELOG.md | sed '1d;$d' >> "$TEMP_CHANGELOG"
          echo "" >> "$TEMP_CHANGELOG"

          # Add all other existing versions
          awk "/^## \[[0-9]/,/^## \[Unreleased\]/ {if (/^## \[Unreleased\]/) exit; print}" CHANGELOG.md >> "$TEMP_CHANGELOG"

          # Extract the Unreleased content for the release notes (BEFORE updating the changelog)
          # Create release notes file with proper content
          echo "# Scene Extrapolation $VERSION" > release_notes.md
          echo "" >> release_notes.md

          # Extract the Unreleased section content (this is what will become the version content)
          sed -n "/^## \[Unreleased\]/,/^## \[/p" CHANGELOG.md | sed '1d;$d' >> release_notes.md

          # If no content was extracted, add a default message
          if [ ! -s release_notes.md ] || [ $(wc -l < release_notes.md) -le 2 ]; then
            echo "## Changes" >> release_notes.md
            echo "" >> release_notes.md
            echo "This release includes various improvements and bug fixes." >> release_notes.md
            echo "" >> release_notes.md
            echo "For detailed changes, see the [changelog](https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md)." >> release_notes.md
          fi

          # Replace the original changelog
          mv "$TEMP_CHANGELOG" CHANGELOG.md

          echo "Updated CHANGELOG.md: moved Unreleased to $VERSION and added new Unreleased section"

      - name: Commit all changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add custom_components/scene_extrapolation/manifest.json
          if [ -f "CHANGELOG.md" ]; then
            git add CHANGELOG.md
          fi
          if [ -f "release_notes.md" ]; then
            git add release_notes.md
          fi

          # Create appropriate commit message based on whether this is a release or just version bump
          if [ "${{ steps.check_release.outputs.should_release }}" == "true" ]; then
            git commit -m "Release ${{ steps.version.outputs.version }}: update version and changelog"
          else
            git commit -m "Bump version to ${{ steps.version.outputs.version }}"
          fi
          git push origin master

      - name: Create Release
        if: steps.check_release.outputs.should_release == 'true'
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "release_notes.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version.outputs.tag }}
          name: "Scene Extrapolation ${{ steps.version.outputs.version }}"
          draft: false
          prerelease: false

      - name: Version Bump Complete
        if: steps.check_release.outputs.should_release == 'false'
        run: |
          echo "✅ Version bump completed successfully!"
          echo "📝 Updated manifest.json to version ${{ steps.version.outputs.version }}"
          echo "ℹ️  No release created (tag message doesn't contain 'release=true')"
          echo "💡 To create a release, include 'release=true' in your tag message:"
          echo "   git tag -a v${{ steps.version.outputs.version }} -m 'Version ${{ steps.version.outputs.version }} release=true'"
